language: node_js

node_js:
  - "8"

cache: npm

# TODO:
# npm test is executed here by default, change it here:
#script:
#  - npm run test:all
#after_success:
#  - npm run coverage:coveralls

deploy:
  provider: npm # deploys to npmjs repo
  email: $NPMJS_ACCOUNT
  api_key: $NPMJS_KEY
  on:
    tags: true # only deploys if a git TAG exists for the commit
    # branch: master # only deploys if branch is master